apiVersion: dex.karavel.io/v1alpha1
kind: DexClient
metadata:
  name: example
  namespace: default
spec:
  name: Example
  redirectUris:
    - https://example.com/oauth/callback
  instanceRef:
    name: github
---
apiVersion: dex.karavel.io/v1alpha1
kind: DexClient
metadata:
  name: example
  namespace: kube-system
spec:
  name: Example
  public: true
  redirectUris:
    - https://example.com/oauth/callback
  instanceRef:
    name: github
    namespace: default
