apiVersion: dex.karavel.io/v1alpha1
kind: DexClient
metadata:
  name: github-example
spec:
  name: GitHub Example
  redirectUris:
    - https://example.com/oauth/callback
  instanceRef:
    name: github
  template:
    metadata:
      labels:
        hello: world
  clientIDKey: GITHUB_CLIENT_ID
  clientSecretKey: GITHUB_CLIENT_SECRET
  issuerURLKey: GITHUB_ISSUER_URL
