apiVersion: dex.karavel.io/v1alpha1
kind: DexClient
metadata:
  name: github-example
spec:
  name: GitHub Example
  redirectUris:
    - https://example.com/oauth/callback
  instanceRef:
    name: github
