apiVersion: dex.karavel.io/v1alpha1
kind: Dex
metadata:
  name: github
spec:
  publicURL: https://dex.example.com/github
  replicas: 1
  ingress:
    annotations:
      cert-manager.io/issuer: selfsigned-issuer
    tlsEnabled: true
  envFrom:
    - secretRef:
        name: github-dex-secrets
  connectors:
    - type: github
      id: github
      name: GitHub
      config: |
        # Credentials can be string literals or pulled from the environment.
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://dex.example.com/github/callback
---
apiVersion: v1
kind: Secret
metadata:
  name: github-dex-secrets
  namespace: default
stringData:
  GITHUB_CLIENT_ID: hello
  GITHUB_CLIENT_SECRET: world
