apiVersion: dex.karavel.io/v1alpha1
kind: Dex
metadata:
  name: github
  namespace: default
spec:
  publicHost: dex.example.com
  replicas: 1
  envFrom:
    - secretRef:
        name: github-dex-secrets
  connectors:
    - type: mockCallback
      id: mock
      name: Example
      config: |
        hello: world
    - type: github
      id: github
      name: GitHub
      config: |
        # Credentials can be string literals or pulled from the environment.
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://dex.example.com/callback
---
apiVersion: v1
kind: Secret
metadata:
  name: github-dex-secrets
  namespace: default
stringData:
  GITHUB_CLIENT_ID: hello
  GITHUB_CLIENT_SECRET: world
