apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
## Append samples you want in your CSV to this file as resources ##
namespace: default
resources:
- client-github.yaml
- client-multiple.yaml
- dex-github.yml
- dex-multiple-connectors.yml
#+kubebuilder:scaffold:manifestskustomizesamples
